name = "felix"
description = "X/Open Native Language System (NLS) for Ada"
version = "0.1.0"

authors = ["Lev Kujawski"]
maintainers = ["Lev Kujawski <int21h@mailbox.org>"]
maintainers-logins = ["lkujaw"]
licenses = "MIT-0"
website = "https://github.com/lkujaw/felix"
tags = ["ada1995", "i18n", "nls",
        "localization", "localisation", "l10n"]

# The underlying interface is dependent upon the Unix C library.
[available.'case(os)']
'windows' = false
